### ISSUE TITLE
Option to get the default url

### ISSUE THREAD

**Issue by philipmarnef** [diesdasdigital/kirby-3-imgix#1]
Imgix standard accounts don't support animated gifs, so it would be nice if there was a way to get the default thumb for some images.

**Comment by philipmarnef** [comment]
Just found out there's a `->mediaUrl()` file method in Kirby, so if you don't need a manipulated file version that's one way to get around the imgix conversion. It solved my particular use case.

**Comment by maxhoffmann** [comment]
Sorry @philipmarnef for the late answer. Just for your information this plugin ignores gifs with version `>=2.0.0`: https://github.com/diesdasdigital/kirby-3-imgix/releases/tag/2.0.0
